// Generated by Wrangler on Tue Jul 30 2024 10:14:04 GMT-0500 (Central Daylight Time)
// by running `wrangler types`

interface Env {
	DISPATCH_NAMESPACE: "testing";
	REQUEST_UNIT_PRICE_NANO_USD: "30000000";
	TOTAL_REQUESTS_PER_UNIT: "1000000";
	INCLUDED_REQUESTS: "100";
	CLOUDFLARE_ACCOUNT_ID: string;
	CLOUDFLARE_API_TOKEN: string;
	BILLING_DURABLE_OBJECT: DurableObjectNamespace<import("./src/index").BillingDurableObject>;
	DISPATCH_NAMESPACE_BINDING: DispatchNamespace;
}
