// Generated by Wrangler on Fri Jul 26 2024 16:52:41 GMT-0500 (Central Daylight Time)
// by running `wrangler types`

interface Env {
	DISPATCH_NAMESPACE: "testing";
	REQUEST_UNIT_PRICE_CENTS: "30";
	TOTAL_REQUESTS_PER_UNIT: "1000000";
	CLOUDFLARE_ACCOUNT_ID: string;
	CLOUDFLARE_API_TOKEN: string;
	BILLING_DURABLE_OBJECT: DurableObjectNamespace<import("./src/index").BillingDurableObject>;
	DISPATCH_NAMESPACE_BINDING: DispatchNamespace;
}
