// Generated by Wrangler on Fri Jun 21 2024 11:03:31 GMT-0500 (Central Daylight Time)
// by running `wrangler types`

interface Env {
	AUTH_TRUST_HOST: true;
	AUTH_SECRET: string;
	GITHUB_APP_NAME: string;
	GITHUB_CLIENT_ID: string;
	GITHUB_CLIENT_SECRET: string;
	DB: D1Database;
}
