// Generated by Wrangler on Fri Jun 21 2024 11:37:24 GMT-0500 (Central Daylight Time)
// by running `wrangler types`

interface Env {
	GITHUB_APP_NAME: string;
	GITHUB_CLIENT_ID: string;
	GITHUB_CLIENT_SECRET: string;
	GITHUB_ACCESS_TOKEN: string;
	DB: D1Database;
}
