-- Migration number: 0001 	 2024-06-18T15:39:07.582Z

CREATE TABLE IF NOT EXISTS user (
  id TEXT NOT NULL PRIMARY KEY,
  github_id NUMBER NOT NULL UNIQUE,
  username TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS session (
  id TEXT NOT NULL PRIMARY KEY,
  expires_at INTEGER NOT NULL,
  user_id TEXT NOT NULL,
  FOREIGN KEY (user_id) REFERENCES user (id)
);
