// Generated by Wrangler on Thu Jul 11 2024 18:24:27 GMT-0500 (Central Daylight Time)
// by running `wrangler types`

interface Env {
	GITHUB_APP_NAME: "Codius Astro Local";
	GITHUB_CLIENT_ID: "Ov23liIuGX3xy486HTL1";
	CF_DISPATCH_NAMESPACE: "testing";
	CLOUDFLARE_ACCOUNT_ID: string;
	CLOUDFLARE_API_TOKEN: string;
	CF_ANALYTICS_API_TOKEN: string;
	GITHUB_CLIENT_SECRET: string;
	GITHUB_ACCESS_TOKEN: string;
	GITHUB_WEBHOOK_SECRET: string;
	STRIPE_TOPUP_PRICE_ID: string;
	STRIPE_SECRET_KEY: string;
	DB: D1Database;
}
