// Generated by Wrangler on Fri Oct 04 2024 16:07:25 GMT-0500 (Central Daylight Time)
// by running `wrangler types`

interface Env {
	GITHUB_APP_NAME: "Codius Astro Local";
	GITHUB_CLIENT_ID: "Ov23liIuGX3xy486HTL1";
	CF_DISPATCH_NAMESPACE: "testing";
	DISPATCHER_HOSTNAME: "coil.app";
	CLOUDFLARE_ACCOUNT_ID: string;
	CLOUDFLARE_API_TOKEN: string;
	GITHUB_CLIENT_SECRET: string;
	GITHUB_ACCESS_TOKEN: string;
	GITHUB_WEBHOOK_SECRET: string;
	STRIPE_TOPUP_PRICE_ID: string;
	STRIPE_SECRET_KEY: string;
	BILLING_DURABLE_OBJECT: DurableObjectNamespace /* BillingDurableObject from dispatcher */;
	DB: D1Database;
}
