on:
  workflow_dispatch:
    inputs:
      appId:
        description: 'Worker App ID'
        required: true
      repo:
        description: 'GitHub repository name'
        required: true
      commit:
        description: 'Git commit hash'
        required: true
      directory:
        description: 'Directory to deploy'
        required: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ${{github.event.inputs.appId}}
        run: echo run identifier ${{ github.run_id }}
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.inputs.repo }}
          ref: ${{ github.event.inputs.commit }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install PNPM if pnpm-lock.yaml is present
        if: hashFiles('${{ github.event.inputs.directory }}/pnpm-lock.yaml') != ''
        uses: pnpm/action-setup@v4
        with:
          version: 9.5.0

      - name: Pull go-toml Docker image
        run: docker pull ghcr.io/pelletier/go-toml:v2

      - name: Sanitize wrangler.toml
        run: |
          mv wrangler.toml wrangler.toml.orig
          docker run -i ghcr.io/pelletier/go-toml:v2 tomljson < wrangler.toml.orig | \
          jq 'del(.d1_databases)' | \
          docker run -i ghcr.io/pelletier/go-toml:v2 jsontoml > wrangler.toml

      - name: Deploy Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: ${{ github.event.inputs.directory }}
          command: deploy --name=${{ github.event.inputs.appId }}
